### ISSUE TITLE
Definir un valor objetivo para la metrica utilizada

### ISSUE THREAD

**Issue by harpomaxx** [FrancoYudica/ia-uncuyo-2024#1]
la metrica Delta E (ΔE) es adecuada, sin embargo se necesita establecer un valor objetivo. Es decir cual será el valor que buscando para dicha metrica. Esto lo vamos a definir durante el desarrollo del proyecto.  Por lo que resulta importante una vez obtenidos los primeros resultados solicitar una consulta temprana para discutirlo.

Por otro lado, es posible que se solicite una evaluacion de pares (compañeros) para evaluar de manera objetiva, mas alla de la metrica elegida cuan cercanos son los resultados respecto a la imagen original.

**Comment by FrancoYudica** [comment]
Estoy de acuerdo, sería difícil establecer un valor objetivo sin tener el programa funcionando, apenas tenga resultados les consultaré con el fin de definirlo.
